version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c "alembic upgrade head && pytest"
    volumes:
      - .:/app
    ports:
      - 8000:80


    depends_on:
      postgres-test:
        condition: service_healthy

  postgres-test:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]