version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 80"
    container_name: fastapi
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]

volumes:
  postgres_data: